services:
  new-app:
    build: newApp
    image: new-app
    container_name: new-app
    ports:
      - "8080:8080"
    depends_on:
      - newDb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://newDb:5433/newdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  oldApp:
    build: oldApp
    image: old-app
    container_name: old-app
    ports:
      - "9090:9090"
    depends_on:
      - oldDb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://oldDb:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  newDb:
    image: postgres:17.5
    container_name: postgres-new-db
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: newdb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  oldDb:
    image: postgres:17.5
    container_name: postgres-old-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

