services:
  newApp:
    build: newApp
    image: new-app
    container_name: new-app
    ports:
      - "8080:8080"
    depends_on:
      - newDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/newdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  oldApp:
    build: oldApp
    image: old-app
    container_name: old-app
    ports:
      - "9090:9090"
    depends_on:
      - oldDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  newDb:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - '5433:5433'

  oldDb:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - ../2. Init Database:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
    ports:
      - '5432:5432'
